### ISSUE TITLE
Soporte Multiplataforma: Linux

### ISSUE THREAD

**Issue by Jhonnymgx115** [jdrodas/AtlasFrutasColombia#1]
Realizar pruebas y ajustes necesarios para garantizar que la aplicación sea compatible con sistemas operativos distintos a Windows, como Linux.

**Comment by jdrodas** [comment]
Hola @Jhonnymgx115 

La arquitectura de la aplicación ya está desacoplada de dependencias propias de los sistemas operativos, por lo que no es necesario realizar ajustes específicos.

Esta versión requiere un entorno de ejecución con .NET framework. Mientras esté instalado en el servidor, la aplicación se ejecutará.
