### ISSUE TITLE
EndPoint para insercion de informacion botánica

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#10]
No hay ruta en el API para ingresar informacion taxonomica

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Hasta el commit a236a3f1251e8771c874f16a42510af775e87b6f, Se tiene ruta para acceder a la parametrización taxonómica (/api/Clasificaciones) . Sobre esta ruta se construirá un endPoint para insertar registros en la sección del modelo relacionado con la información botánica.

Ya se tiene construido el modelo Clasificación, por lo que se puede utilizar para para las demás operaciones CRUD pendientes.

**Comment by jdrodas** [comment]
Hola @hrcamilo11,

Se ha implementado en el controlador de Clasificaciones los métodos para insertar y eliminar jerarquías taxonómicas que serán asociadas a las frutas.

A nivel de Swagger se ve asi:

<img width="1094" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/6e60afd8-50ae-4b04-9b66-d68596b1d60f">

En el repositorio se crearon estos dos métodos para manejar la inserción y la eliminación:

<img width="434" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/92ea3104-ed77-4b66-8e20-3772c3871685">

A nivel de base de datos, se crearon los siguientes procedimientos almacenados:

<img width="618" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/3363e37e-c8c8-4b44-9b5b-dce4dbd96291">
