### ISSUE TITLE
EndPoint para inserción de información nutricional de la fruta

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#11]
Insertar nutricion de fruta

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Para lograr este propósito, en el controlador de las frutas se creó un nuevo método denominado CreateNutritionDetailsAsync que está asociado al método POST con los siguientes parámetros.

<img width="808" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/c5bccdfb-9f86-4aac-9bf1-4bcf83cebb32">

Este método se propagó en el resto de las capas hasta poder invocar el procedimiento almacenado "p_inserta_nutricion_fruta"
