### ISSUE TITLE
EndPoint para actualización de información nutricional de la fruta

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#12]
Actualizar información nutricional de fruta

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Para lograr este propósito, en el controlador de las frutas se creó un nuevo método denominado UpdateNutritionDetailsAsync que está asociado al método PUT con los siguientes parámetros.

<img width="806" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/632a348d-f371-4bce-bdcc-2a2851fc544b">

Este método se propagó en el resto de las capas hasta poder invocar el procedimiento almacenado "p_actualiza_nutricion_fruta"
