### ISSUE TITLE
EndPoint para eliminación de información nutricional de la fruta

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#13]
Eliminar información nutricional de fruta

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Para lograr este propósito, en el controlador de las frutas se creó un nuevo método denominado RemoveAsync que está asociado al verbo HTTP DELETE con los siguientes parámetros.

<img width="537" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/d4d941d3-f14b-4929-8168-0cd8b209d067">

Este método se propagó en el resto de las capas hasta poder invocar el procedimiento almacenado "p_elimina_nutricion_fruta"

**Comment by jdrodas** [comment]
Cerrado con commit https://github.com/jdrodas/AtlasFrutasColombia/commit/9ac2bf963ff8ae5c47c058e7ca371846762d5e4d
