### ISSUE TITLE
EndPoint para inserción de informacion taxonómica de la fruta

### ISSUE THREAD

**Issue by 1pperalta** [jdrodas/AtlasFrutasColombia#14]
Insertar taxonomia de fruta

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Para lograr este propósito, en el controlador de las frutas se creó un nuevo método denominado RemoveAsync que está asociado al verbo HTTP DELETE con los siguientes parámetros.

<img width="537" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/d4d941d3-f14b-4929-8168-0cd8b209d067">

Este método se propagó en el resto de las capas hasta poder invocar el procedimiento almacenado "p_elimina_nutricion_fruta"

**Comment by jdrodas** [comment]
Hola!

En el controlador FrutasController se realizaron varios endPoints para manejar la clasificación taxonómica de la fruta:

<img width="683" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/c49327a4-c439-4648-b20f-ec63cd5c4234">


Para la inserción, se creó el método **CreateTaxonomicDetailsAsync** utilizando el procedimiento almacenado p_inserta_taxonomia_frutas.
