### ISSUE TITLE
EndPoint para actualización de informacion de producción de la fruta

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#15]
El API debe realizar la actualización de información de producción.
Se debe validar la fruta (Que exista).
Se debe validar por:
- Municipio
- Clima
- Epoca
Luego de la validación, si la epoca aún no esta creada, debe insertarse.

**Comment by jdrodas** [comment]
Hola @hrcamilo11 
Este endPoint no será implementado. En su lugar tenemos para consultar la producción de una fruta, insertarla o borrarla.

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/1e9af3b5-1207-4cb5-b560-42bb9e50fab8)

Si una información de producción quedó errónea, simplemente eliminarla e insertarla nuevamente,
