### ISSUE TITLE
EndPoint para inserción de informacion de épocas

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#16]
El API debe validar si la epoca existe, y si aún no esta creada debe insertarlo.

**Comment by jdrodas** [comment]
Hola @hrcamilo11 !

Se creó en la ruta del controlador epocasController, el endPoint para la inserción de época, la cual ejecuta el procedimiento almacenado **p_inserta_epoca** a nivel de base de datos postgreSQL:

<img width="473" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/5fef5b46-990b-4470-8f35-0bed793c41a6">
