### ISSUE TITLE
EndPoint para eliminación de informacion de producción de la fruta

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#18]
El API debe eliminar la información de producción de una fruta.

**Comment by jdrodas** [comment]
Hola @hrcamilo11 

Se ha implementado el endpoint para eliminar la producción de una fruta. Está asociado al procedimiento almacenado **p_elimina_produccion_fruta**:

En total, se crearon endPoints para crear, consultar y eliminar producción de fruta:

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/0ea85349-c044-401b-9181-9cfe811ebae3)
