### ISSUE TITLE
Climas pueden tener alturas con valores negativos 

### ISSUE THREAD

**Issue by hrcamilo11** [jdrodas/AtlasFrutasColombia#31]
El procedimiento de validación en la creación y actualización de climas no permite valores negativos.

Existen climas en alturas por debajo del nivel del mar.

Ejemplo.

Clima: Calor insoportable 
Altura mínima -100
Altura máxima 0

**Comment by jdrodas** [comment]
Hola @hrcamilo11 

Efectivamente si se coloca una definición de clima como la propones:

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/76edb5f3-c414-451a-8645-a13e072a89af)

Se obtiene el resultado siguiente:

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/430ef944-b3cd-458e-b1f7-508ef6d40c45)

Si bien es una situación posible para algunas ciudades en el mundo, en Colombia no tenemos oficialmente ningún municipio con altitud por debajo del nivel del mar:

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/62387538-1af2-416a-b941-8bb84572fedb)

Por favor documéntame una población en Colombia que produzcas frutas para darle prioridad a este requerimiento.

**Comment by jdrodas** [comment]
Hola @hrcamilo11 

A 2024, no se tiene ningún territorio en Colombia con producción de frutas que no sea costero, que esté bajo el nivel del mar, o sea, alturas negativas.

Por lo tanto este requerimiento no será implementado en esta oportunidad.
