### ISSUE TITLE
Consultar frutas por clima

### ISSUE THREAD

**Issue by Kolark** [jdrodas/AtlasFrutasColombia#4]
Seria bueno consultar que frutas se cosechan por clima.

**Comment by jdrodas** [comment]
Hola @Kolark !

Para implementar esta opción necesitaremos:

- Crear un endPoint para los climas
- Poder consultar por un clima específico
- Poder consultar que frutas se producen en ese clima

**Comment by jdrodas** [comment]
Hola @Kolark !

La implementación realizada permitió obtener el siguiente resultado:

<img width="1008" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/f6047286-dada-4471-8016-d47f8fbefc23">

Al igual que otros Servicios, le delegamos al repositorio de frutas la responsabilidad de identificar cuales se producen en un clima específico, permitiendo que el ClimaService acceda al repositorio de frutas:

<img width="581" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/bc71e9f9-45a0-4c65-8c3d-1e842b0de3a2">

Finalmente en el repositorio se implementaron métodos para obtener las frutas por clima y específicamente las producciones asociadas al clima seleccionado, ya que una fruta puede producirse en varios climas:

<img width="854" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/dd55d8be-e09e-4cbd-91b6-ea67cb34b1c5">

**Comment by jdrodas** [comment]
Solucionado con commit 3a76218d807169303e2b7dd317003cc353be6f41
