### ISSUE TITLE
Consultar frutas por municipios

### ISSUE THREAD

**Issue by mquijanoj09** [jdrodas/AtlasFrutasColombia#5]
Para el API se espera poder obtener la lista de producción de las frutas por un municipio seleccionado.

Quisiera conocer para cada fruta:

Su información Taxonomica
Su informacion Nutricional
Su información de epocas y climas donde se produce

**Comment by jdrodas** [comment]
Hola @mquijanoj09 !

Para implementar esta opción, necesitaremos:

- EndPoint para los Municipios
- Seleccionar un municipio en particular
- Obtener las frutas producidas allí

**Comment by jdrodas** [comment]
Hola!

Se implementó el endPoint para consultar municipios, específicamente las frutas producidas.

![image](https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/208f746e-d994-4d00-9600-46af144a8fa5)

Hasta el momento solo se tiene información de producción, pero al crear un modelo para una FrutaDetallada, en la medida en que se implementen las consultas sobre la información taxónomica y nutricional, la respuesta se actualizará de manera acorde.
