### ISSUE TITLE
Consultar frutas por género taxonómico

### ISSUE THREAD

**Issue by GarcesMJM** [jdrodas/AtlasFrutasColombia#6]
Hola!! 
Se esperaría poder consultar las frutas que hay por cada género, además de las especies pertenecientes a estos.

**Comment by jdrodas** [comment]
Hola @GarcesMJM !

Para implementar esa solución, se crearon endPoints adicionales para la ruta de Clasificaciones.

Las clasificaciones se llevaron a nivel de generos y luego de seleccionar un genero específico, se obtiene la colección de fruta clasificadas:

<img width="923" alt="image" src="https://github.com/jdrodas/AtlasFrutasColombia/assets/29258977/3c0babe0-5efb-4381-8fb0-104c5381ba31">

Se creó una clase denominada **FrutaClasificada**, la cual solo tiene la información de la clasificación taxonómica de la fruta.
