### ISSUE TITLE
Error Messages. XSS (Visualización de datos reflejados)

### ISSUE THREAD

**Issue by SanTacrZ** [jdrodas/AtlasFrutasColombia#8]
Errores "NotFound": Las respuestas "NotFound" en GetByIdAsync y GetAssociatedMunicipiosAsync son vulnerables a XSS si el mensaje de error (error.Message) no está codificado.

Si un atacante puede controlar este mensaje, podría inyectar scripts maliciosos que se ejecutan en el navegador del usuario.

// Vulnerable (por ejemplo, no para uso real)
return NotFound($"<script>alert('XSS Attack!')</script>{error.Message}");

 En tu controlador DepartamentosController, tienes dos métodos que manejan la respuesta NotFound:

**Comment by jdrodas** [comment]
Hola @SanTacrZ,

Necesito documentación de como este tipo de vulnerabilidad se logra en este código de la aplicación. Sería muy bueno que me documentaras el caso más detalladamente.

Mientra tanto, este issue no será resuelto.

Saludos,

**Comment by SanTacrZ** [comment]
Bueno señor
